const PLAYER_JOINED = "PLAYER_JOINED"
const GAME_REQUEST = "GAME_REQUEST"
const GAME_MULTIPLAYER = "GAME_MULTIPLAYER"
const GAME_SINGLEPLAYER = "GAME_SINGLEPLAYER"

module.exports = {
    PLAYER_JOINED,
    GAME_REQUEST,
    GAME_MULTIPLAYER,
    GAME_SINGLEPLAYER,
}
