const PLAYER_JOINED = "PLAYER_JOINED"
const GAME_REQUEST = "GAME_REQUEST"
const NEW_QUESTION_SINGLEPLAYER = "NEW_QUESTION_SINGLEPLAYER"
const GAME_MULTIPLAYER = "GAME_MULTIPLAYER"

module.exports = {
    PLAYER_JOINED,
    GAME_REQUEST,
    NEW_QUESTION_SINGLEPLAYER,
    GAME_MULTIPLAYER,
}