const PLAYER_JOINED = "PLAYER_JOINED"
const GAME_REQUESTED = "GAME_REQUESTED"
const GAME_REQUEST_ANSWERED = "GAME_REQUEST_ANSWERED"
const NEW_QUESTION_SINGLEPLAYER = "NEW_QUESTION_SINGLEPLAYER"
const GAME_MULTIPLAYER = "GAME_MULTIPLAYER"
const NEW_QUESTION_MULTIPLAYER = "NEW_QUESTION_MULTIPLAYER"
const NEW_ANSWER_MULTIPLAYER = "NEW_ANSWER_MULTIPLAYER"
const SCORE_UPDATED = "SCORE_UPDATED"

module.exports = {
    PLAYER_JOINED,
    GAME_REQUESTED,
    GAME_REQUEST_ANSWERED,
    NEW_QUESTION_SINGLEPLAYER,
    GAME_MULTIPLAYER,
    NEW_QUESTION_MULTIPLAYER,
    NEW_ANSWER_MULTIPLAYER,
    SCORE_UPDATED,
}