const LOBBY_PLAYERS_SUBSCRIPTION = "LOBBY_PLAYERS_SUBSCRIPTION"
const LOBBY_PING = 'LOBBY_PING'
const GAME_REQUEST = "GAME_REQUEST"
const GAME_MULTIPLAYER = "GAME_MULTIPLAYER"
const GAME_SINGLEPLAYER = "GAME_SINGLEPLAYER"

export {
    LOBBY_PLAYERS_SUBSCRIPTION,
    GAME_REQUEST,
    GAME_MULTIPLAYER,
    GAME_SINGLEPLAYER,
    LOBBY_PING
}
