version: 0.0
os: linux
files:
  - source: package.json
    destination: /srv
  - source: ecosystem.config.js
    destination: /srv
  - source: dist
    destination: /srv/dist
  - source: .env.production
    destination: /srv
  - source: production-start.js
    destination: /srv
hooks:
  AfterInstall:
    - location: prod-scripts/remove-node_modules.sh
      runas: ubuntu
      timeout: 300
    - location: prod-scripts/npm-install.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: prod-scripts/start.sh
      runas: ubuntu
      timeout: 60
