version: 0.0
os: linux
files:
  - source: package.json
    destination: /srv
  - source: index.js
    destination: /srv
  - source: .env.production
    destination: /srv
  - source: ecosystem.config.js
    destination: /srv
hooks:
  AfterInstall:
    - location: prod-scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: prod-scripts/start.sh
      runas: root
      timeout: 60
