name: clients/assets Production Build
on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - "assets/**"
      - ".github/workflows/clients-assets-production.yml"
jobs:
  deploy-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: assets.enlighten.rip
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: "clients/assets/public"
      - name: Invalidate cache
        uses: awact/cloudfront-action@0.1.2
        env:
          DISTRIBUTION_UD: E3VHFUB65O18V2
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
