name: clients/app Pull Request
on:
  pull_request:
    branches:
      - master
    paths:
      - "clients/app/**"
      - ".github/workflows/clients-app-pr.yml"
jobs:
  test-app:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install (Client)
        run: |
          npm install
        working-directory: clients/app
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: http://localhost:8000
          working-directory: clients/app
      - name: Run Jest
        run: |
          npm test -- --watchAll=false
        working-directory: clients/app
      - name: Build
        run: |
          npm run build
        working-directory: clients/app
