name: services/bff Pull Request
on:
  pull_request:
    branches:
      - master
    paths:
      - "services/bff/**"
      - ".github/workflows/services-bff-pr.yml"
jobs:
  test-bff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install npm dependencies
        run: npm install
        working-directory: services/bff
      - name: Build
        run: npm run build:prod
        working-directory: services/bff
      - name: Test
        run: npm run test
        working-directory: services/bff
