name: services/bff Pull Request
on:
  pull_request:
    branches:
      - master
    paths:
      - "services/bff/**"
      - ".github/workflows/services-bff-pr.yml"
jobs:
  test-bff:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies - libraries
        run: for d in ./libraries/*/ ; do (cd "$d" && yarn); done
      - name: Install dependencies
        run: yarn
        working-directory: services/bff
      - name: Build
        run: yarn build:prod
        working-directory: services/bff
      - name: Test
        run: yarn test
        working-directory: services/bff
